---
label: base
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: list
  name: images
  label: images
- type: list
  name: tags
  label: tags
- type: list
  name: categories
  label: categories
pages:
- content/posts/header.md
