---
label: base
hide_body: false
fields:
- type: list
  name: categories
  label: categories
- type: datetime
  name: date
  label: date
- type: boolean
  name: meta
  label: meta
- type: list
  name: tags
  label: tags
- type: text
  name: title
  label: title
pages:
- content/posts/Provisioning a Lambda function using Terraform.md
- content/posts/ebs.md
